config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  resources :comments
  resources :sessions, only: %i[create]
  resources :claps, only: %i[create]
  root 'users#show'
  post 'users/login', to: 'users#login'
  post 'session/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :verify_token

    def verify_token
      redirect_to users_login_path if session[:current_user].nil?
    end
end

app/controllers/claps_controller.rb
class ClapsController < ApplicationController

    def create
        url = Rails.application.credentials[:services][:post] + '/api/claps'
        payload = {clap: {user_id: session[:current_user]['user_id'], clapable_id: params['clapable_id'],clapable_type: params['clapable_type']}}
        response = RestClient::Request.execute method: :post, url: url, action: :create, payload: payload do |response, request|
            redirect_to post_path params['post_id']
        end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :verify_token

    def create
        url = Rails.application.credentials[:services][:post] + '/api/comments/'
        payload = { comment: {
            comment: params[:comment],
            post_id: params[:post_id],
            user_id: params[:user_id]
        }}
        response = RestClient.post url, payload.to_json, content_type: 'application/json'
        @comment = JSON.parse(response.body)
        redirect_to post_path(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :verify_token

    def index
        payload = {title: params['title']}
        url = Rails.application.credentials[:services][:post] + '/api/posts'
        response = RestClient::Request.execute method: :get, url: url, action: :index, payload: payload do |response, request|
            @posts = JSON.parse(response)['posts']
            respond_to do |format|
                format.html
                format.js
            end
        end
    end

    def create
        url = Rails.application.credentials[:services][:post] + '/api/posts'
        payload = {post: {title: params['title'],description: params['description'],user_id: session[:current_user]['user_id']}}
        response = RestClient.post(url, payload.to_json, {'content-type' => 'application/json'}) do |response, request|
            if response.code == 200
                redirect_to posts_path
            end
        end
    end

    def new
    end

    def show
        @post = find_post_by_id params[:id]
        url = Rails.application.credentials[:services][:post] + '/api/comments/'
        response = RestClient.get url, { params: {post_id: @post["id"] }}
        @comments = JSON.parse(response.body)['comments']
    end

    def update
        url = Rails.application.credentials[:services][:post] + '/api/posts/' + params[:id]
        payload = { post: {title: params[:title], description: params[:description], user_id: params[:user_id]}}
        RestClient::Request.execute method: :patch, url: url, action: :update, payload: payload do |response, request|
            flash[:success] = JSON.parse(response.body)["message"]
            redirect_to posts_path
        end
    end

    def destroy
        post = find_post_by_id(params["id"])
        redirect_to posts_path if !user_has_post_rights? post["user_id"]
        url = Rails.application.credentials[:services][:post] + '/api/posts/' + params[:id]
        RestClient::Request.execute method: :delete, url: url, action: :destroy do |response, request|
            flash[:success] = JSON.parse(response.body)["message"]
            redirect_to posts_path
        end
    end

    def edit
        @post = find_post_by_id(params["id"])
        redirect_to posts_path if !user_has_post_rights? @post["user_id"]
    end

    private
    def user_has_post_rights? user_id_from_post
        return true if user_id_from_post == session[:current_user]["user_id"]
        false
    end

    def find_post_by_id post_id
        url = Rails.application.credentials[:services][:post] + '/api/posts/' + post_id
        RestClient::Request.execute method: :get, url: url, action: :show do |response, request|
            @post = JSON.parse(response.body)["post"]
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def destroy
        session.delete(:current_user)
        redirect_to users_login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_token

    def create
        url = Rails.application.credentials[:services][:user] + '/api/users'
        payload = {user: {name: params["name"],email: params["email"],password: params["password"]}}
        response = RestClient.post(url, payload.to_json, {'content-type' => 'application/json'}) do |response, request|
            if response.code == 200
                redirect_to users_login_path, method: :post
            else
                message = JSON.parse(response)["errors"]["email"][0]
                flash[:alert] = "Email " + message
                redirect_to users_path
            end
         end
    end

    def login
        url = Rails.application.credentials[:services][:user] + '/login'
        payload = {user: {email: params["email"],password: params["password"]}}
        response = RestClient.post(url, payload.to_json, {'content-type' => 'application/json'}) do |response, request|
            response = JSON.parse(response.body)
            if  response['user_id'] && response['user_email'] && response['auth_token']
                session[:current_user] = response
                redirect_to posts_path, method: :get
            else
                redirect_to users_login_path, alert: response['message']
            end
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def find_user_by_id id
        url = Rails.application.credentials[:services][:user] + '/api/users/' + id
        response = RestClient::Request.execute method: :get, url: url, action: :show do |response, request|
            JSON.parse(response.body)['user']
        end
    end

    def find_current_user
        session[:current_user]
    end

    def get_clap_count clapable_id, type
        url = Rails.application.credentials[:services][:post] + '/api/claps'
        payload = {clapable_id: clapable_id,clapable_type: type}
        RestClient::Request.execute method: :get, url: url, action: :index, payload: payload do |response, request|
            JSON.parse(response.body)['claps']
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <% if session[:current_user].present? %>
      <div class="about-section">
        <h2>Blogs</h2>
      </div>
      <div class="topnav">
        <%= link_to "Home", posts_path, class: 'btn postcard-btn' %>
        <%= link_to "New", new_post_path, class: 'btn postcard-btn' %>
        <%= link_to "Logout", session_logout_path, method: :post, class: 'btn postcard-btn' %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_all_posts.html.erb
<% if flash.now[:success] %>
    <div class="alert alert-success" role="alert">
        <%= flash.now[:success] %>
    </div>
<% end %>
<div id="updated">
    <% @posts.each do |post| %>
        <% user = find_user_by_id post["user_id"].to_s %>
        <div class="card">
            <div class="postcard-title"><%= post['title'].capitalize %></div>
            <% if find_current_user["user_email"] == user['email'] %>
                <div class="postcard-del">
                    <%= link_to edit_post_path(post['id']) do %>
                        <i class="fa fa-pencil-square-o" id = "edit"></i>
                    <% end %>
                    <%= link_to post_path(post['id']),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } do
                    %>
                    <i class="fa fa-trash" id = "delete" aria-hidden="true"></i>
                    <% end %>
                </div>
            <% end %>
            <div class="postcard-desc"> <%=  post['description'] %></div>
            <div class="postcard-claps">
            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
            <%= get_clap_count(post['id'],"Post")%>
                <%= link_to "View", post_path(post['id']), class: 'btn postcard-btn' %>
            </div>
            <div class = "name"><h3>- <%= user["email"] %></h3></div>
            <div class = "name"><%= post["created_at"].to_date %></div>
        </div>
    <% end %>
</div>

app/views/posts/edit.html.erb
<% if flash[:notice] %>
  <div class="notification is-primary global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<%= flash.now[:success] %>
<%= form_with url: post_path(), method: :patch do |form| %>
    <div class="container">
        <h1>Edit Post</h1>
        <hr>
        <%= form.text_field :title ,value: @post['title'], required: "required"%>
        <%= form.text_area :description ,value: @post['description'], class: "description", required: "required"%>
        <%= form.hidden_field :user_id, value: @post['user_id'] %>
        <hr>
        <%= form.submit "Update", class: "registerbtn"%>
    </div>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <div class="post-container">
    <%= form_with url: posts_path , method: :get , remote: true  do |form| %>
      <div class="search-bar">
        <%= form.text_field :title ,placeholder: "Search post"%>
        <%= form.submit "Search", :class => "register-btn"%>
      </div>
    <% end %>
  </div>
    <%= render partial: 'all_posts' %>
</div>

app/views/posts/index.js.erb
document.getElementById("updated").innerHTML = ("<%=j render partial: "all_posts" %>");

app/views/posts/new.html.erb
<% if flash[:notice] %>
  <div class="notification is-primary global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<%= flash.now[:success] %>
<%= form_with url: posts_path    do |form| %>
    <div class="container">
        <h1>Create Post</h1>
        <hr>
        <%= form.text_field :title ,placeholder: "Enter Title", required: "required"%>
        <%= form.text_area :description ,class: "description",placeholder: "Enter Description", required: "required"%>
        <hr>
        <%= form.submit :class => "registerbtn",:value => "Save"%>
    </div>
<% end %>

app/views/posts/show.html.erb
<div class="post">
    <div class="post-container">
        <div class="post-title"><h3><%= @post['title'].capitalize %></h3></div>
        <div class="post-desc">
            <%= @post['description'] %>
        </div>
        <div class="post-claps">
            <%= link_to claps_path({params: {clapable_id: @post['id'], clapable_type: "Post", post_id: @post['id']}}),
                        method: :create do 
            %>  
                <i class="fa fa-thumbs-up" aria-hidden="true"></i>
            <% end %>
            <%= get_clap_count(@post['id'],"Post")%>
        </div>
        <% user = find_user_by_id @post["user_id"].to_s %>
        <div class = "name"><h3>- <%= user["email"] %></h3></div>
        <div class = "name"><%= user["created_at"].to_date %></div>
        <div class="comment">
            <div class="comment-new">
                <h4>Leave a comment</h4>
                <%= form_with url: comments_path do |form| %>
                    <%= form.hidden_field :post_id, value: @post['id'] %>
                    <%= form.hidden_field :user_id, value: session[:current_user]["user_id"] %>
                    <%= form.text_area :comment ,class: "form",placeholder: "Enter Comment", required: "required"%>
                    <%= form.submit "Comment", class: "register-btn"%>
                <% end %>
            </div>
            <% @comments.each do |comment| %>
                <div class="comment-block">
                    <div class="comment-from"><%= (find_user_by_id comment["user_id"].to_s)['email'] %></div>
                    <div class="comment-text"><%= comment['comment'] %></div>
                    <div class="comment-timestamp"><%= comment['created_at'].to_time.strftime('%e %b at %l:%M %p') %></div>
                    <div class="comment-claps">
                        <%= link_to claps_path({params: {clapable_id: comment['id'],clapable_type: "Comment", post_id: @post['id']}}),
                                    method: :create do 
                        %>  
                            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                        <% end %>
                        <%= get_clap_count(comment['id'],"Comment")%>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

<style>
    .fa-thumbs-up:before {
        content: "\f164";
        color: burlywood;
        font-size: xx-large;
    }
</style>

app/views/users/index.html.erb
<% if flash.now[:alert] %>
    <div class="alert alert-warning" role="alert">
        <%= flash.now[:alert] %>
    </div>
<% end %>
<%= form_with url: users_path do |form| %>
    <div class="container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>
        <%= form.text_field :name ,placeholder: "Enter Name", required: "required"%>
        <%= form.text_field :email ,placeholder: "Enter Email", required: "required", pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"%>
        <%= form.password_field :password ,placeholder: "Enter Password", required: "required"%>
        <hr>
        <%= form.submit "Register", :class => "registerbtn"%>
    </div>
    <div class="container signin">
        Already have an account? <%= link_to "LogIn", users_login_path %>
    </div>
<% end %>

app/views/users/show.html.erb
<% if flash.now[:alert] %>
    <div class="alert alert-warning" role="alert">
        <%= flash.now[:alert] %>
    </div>
    <% end %>
<%= form_with url: users_login_path do |form| %>
    <div class="container">
        <h1>Login</h1>
        <hr>
        <%= form.text_field :email ,placeholder: "Email", required: "required"%>
        <%= form.password_field :password ,placeholder: "Password", required: "required"%>
        <hr>
        <%= form.submit "Login", :class => "registerbtn"%>
    </div>
    <div class="container signin">
        Not signed up yet?  <%= link_to "Register", users_path %><p/>
    </div>
<%end%>